### ISSUE TITLE
TypeError: Cannot read property 'toLocaleString' of null

### ISSUE THREAD

**Issue by N3mines** [chipx86/butte-covid19-dashboard#1]
Hover pop up that says "TypeError: Cannot read property 'toLocaleString' of null"

Opening up the website and inspecting element, I have two errors
* `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
* `TypeError: Cannot read property 'toLocaleString' of null
    at n (main.516fef95.js:1)
    at Object.BC19.setCounter (main.516fef95.js:1)
    at Object.BC19.setupCounters (main.516fef95.js:1)
    at main.516fef95.js:1`

In addition to these two errors, no data or graphs load up when opening the website.

**Comment by chipx86** [comment]
So sorry about that! There was an error with some auto-updated data that contained a `null` instead of a number. I'm bullet-proofing the importer for this to ensure it will reject any updates with this issue.

It should be working now.

**Comment by N3mines** [comment]
Thanks for the fix!  Love the work you've done to the website, it's been an awesome set of visuals over the past year :)
